#!/bin/bash
# compile debug


#g++ -std=c++20 -Wall -Wextra -Wno-non-template-friend -pedantic -Werror -fsanitize=address,undefined -O0  main.cpp -o __run__ -lgmp -lgmpxx
g++ -std=c++20 -Wall -Wextra -Wno-non-template-friend -pedantic -Werror -fwhole-program -march=native -O2  main.cpp -o __run__ -lgmp -lgmpxx

endl=""
args=""

if test -f __run__
then
echo "It COMPILES! MUAHAHAHAHAHAHA"
chmod 777 __run__
./__run__
rm __run__;
fi